---
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - stable
  - name: beta
    prerelease: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - "@semantic-release/github"
