name: 'Setup yq environment'
description: 'GitHub Action to setup the `jq` and `yq` command for yaml and json parsing'
author: 'shiipou'

outputs:
  yq-binary:
    description: 'The pinary path for the yq command'
    value: ${{ steps.install-yq.outputs.yq-binary }}
    
runs:
  using: "composite"
  steps:
    - name: Install yq
      id: install-yq
      shell: bash
      env:
        PARAMS: '${{ inputs.params }}'
        GO_VERSION: 1.17.6
      run: |
        curl -sSLo go.tar.gz https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
        tar -xzf go.tar.gz
        rm go.tar.gz
        
        echo "PATH=${PATH}:${PWD}/go/bin" >> $GITHUB_ENV
        
        go version
        
        sudo unlink /usr/bin/go
        sudo ln -s $PWD/go/bin/go /usr/bin/go
        
        go version
        
        GO111MODULE=on go get github.com/mikefarah/yq/v4
        
        echo "::set-output name=yq-binary::${PWD}/go/bin/yq"
