name: 'Setup yq environment'
description: 'GitHub Action to setup the `jq` and `yq` command for yaml and json parsing'
author: 'shiipou'

runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: bash
      en:v
        PARAMS: '${{ inputs.params }}'
      run: |
        if [ $(whereis pip | cut -d":" -f2) ]; then
          apt update && apt install -y python3 python3-pip
        fi
        pip3 install jq yq
